### ISSUE TITLE
Website Crashes on Google Chrome Andriod

### ISSUE THREAD

**Issue by foxy4096** [Visualway/Vitary#12]
**Describe the bug**
When the website is accessed from Google Chrome Android The Site **Crashes**

**To Reproduce**
1. Go to https://bit.ly/vitary on Google Chrome Android
2. The website will cause the browser to crash 

**Expected behavior**
The website should open as normally as it work on desktop
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 96.0.1054.34 (Official build) (64-bit)
 - It works on Desktop and on other mobile browser like Mozilla Firefox

**Smartphone (please complete the following information):**
 - Device: OPPO F11
 - OS: Android 11
 - Browser: Google Chrome
 - Version: 96.0.4664.104

**Additional context**
Works on any other browser like Mozilla Firefox etc

**Comment by foxy4096** [comment]
https://stackoverflow.com/questions/70508044/django-app-is-crashing-chrome-browser-on-android

**Comment by RainboeStrykr** [comment]
**This bug has been solved.** 

**If you are facing this buy, please update your chrome browser.**

**Versions supported: 97.0.4692.87 and above**

**Comment by foxy4096** [comment]
This issue seems to happen on Android Device with Version greater than 9 [Pie]
